"""
Generated by nlsc from examples/showcase/mission_control.nl
Module: mission_control
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Optional

import math


@dataclass
class Waypoint:
    code: str
    name: str
    x: float
    y: float
    science: float
    sample_kg: float
    dwell_hours: float

    def __post_init__(self):
        if not self.code:
            raise ValueError('code is required')
        if not self.name:
            raise ValueError('name is required')
        if self.science < 0:
            raise ValueError('science must be at least 0')
        if self.sample_kg < 0:
            raise ValueError('sample_kg must be at least 0')
        if self.dwell_hours < 0:
            raise ValueError('dwell_hours must be at least 0')


@dataclass
class Rover:
    battery: float
    reserve_percent: float
    payload_limit: float
    pace: str
    weather: str

    def __post_init__(self):
        if self.battery < 20:
            raise ValueError('battery must be at least 20')
        if self.battery > 240:
            raise ValueError('battery must be at most 240')
        if self.reserve_percent < 10:
            raise ValueError('reserve_percent must be at least 10')
        if self.reserve_percent > 40:
            raise ValueError('reserve_percent must be at most 40')
        if self.payload_limit < 5:
            raise ValueError('payload_limit must be at least 5')
        if self.payload_limit > 90:
            raise ValueError('payload_limit must be at most 90')
        if not self.pace:
            raise ValueError('pace is required')
        if not self.weather:
            raise ValueError('weather is required')
        if not (self.pace in ['Eco', 'Traverse', 'Sprint']):
            raise ValueError("Invariant violated: pace in ['Eco', 'Traverse', 'Sprint']")
        if not (self.weather in ['Clear', 'Dust', 'Storm']):
            raise ValueError("Invariant violated: weather in ['Clear', 'Dust', 'Storm']")


@dataclass
class Readiness:
    status: str
    can_launch: bool
    distance: float
    hours: float
    energy: float
    remaining: float
    reserve: float
    energy_margin: float
    payload: float
    payload_margin: float
    science: float

    def __post_init__(self):
        if self.distance < 0:
            raise ValueError('distance must be at least 0')
        if self.hours < 0:
            raise ValueError('hours must be at least 0')
        if self.energy < 0:
            raise ValueError('energy must be at least 0')
        if self.reserve < 0:
            raise ValueError('reserve must be at least 0')
        if self.payload < 0:
            raise ValueError('payload must be at least 0')
        if self.science < 0:
            raise ValueError('science must be at least 0')


@dataclass
class Leg:
    destination: str
    code: str
    x: float
    y: float
    distance: float
    energy: float
    hours: float
    science: float

    def __post_init__(self):
        if self.distance < 0:
            raise ValueError('distance must be at least 0')
        if self.energy < 0:
            raise ValueError('energy must be at least 0')
        if self.hours < 0:
            raise ValueError('hours must be at least 0')
        if self.science < 0:
            raise ValueError('science must be at least 0')


def base() -> Any:
    """
    Locate the rover's starting point and required return destination.

    Returns:
        Waypoint("base", "Aster Base", 0, 0, 0, 0, 0)
    """
    return Waypoint("base", "Aster Base", 0, 0, 0, 0, 0)


def catalog() -> Any:
    """
    Offer six fictional survey sites with explicit scientific and payload tradeoffs.

    Returns:
        [Waypoint("basalt", "Basalt Gate", 6, 3, 18, 4, 0.5), Waypoint("echo", "Echo Crater", 12, 9, 38, 9, 1.2), Waypoint("glass", "Glass Dunes", 20, 5, 26, 6, 0.8), Waypoint("ridge", "North Ridge", 8, 19, 42, 11, 1.5), Waypoint("delta", "Delta Shelf", 21, 20, 58, 15, 2), Waypoint("relay", "Relay Spire", 3, 12, 22, 3, 0.4)]
    """
    return [Waypoint("basalt", "Basalt Gate", 6, 3, 18, 4, 0.5), Waypoint("echo", "Echo Crater", 12, 9, 38, 9, 1.2), Waypoint("glass", "Glass Dunes", 20, 5, 26, 6, 0.8), Waypoint("ridge", "North Ridge", 8, 19, 42, 11, 1.5), Waypoint("delta", "Delta Shelf", 21, 20, 58, 15, 2), Waypoint("relay", "Relay Spire", 3, 12, 22, 3, 0.4)]


def distance_between(origin: Waypoint, destination: Waypoint) -> Any:
    """
    Measure the straight-line distance between two sites in kilometers.

    Args:
        origin: Waypoint
        destination: Waypoint

    Returns:
        math.sqrt(dx * dx + dy * dy)
    """
    dx = destination.x - origin.x
    dy = destination.y - origin.y
    return math.sqrt(dx * dx + dy * dy)


def route_distance(route: list[Waypoint], origin: Waypoint, cursor: Optional[float] = None) -> Any:
    """
    Recursively total an ordered route, always including its return to base.

    Args:
        route: list of Waypoint
        origin: Waypoint
        cursor: number

    Returns:
        distance
    """
    if cursor is not None:
        index = cursor
    else:
        index = 0
    if index >= len(route):
        distance = distance_between(origin, base())
    else:
        distance = distance_between(origin, route[index]) + route_distance(route, route[index], index + 1)
    return distance


def science_total(route: list[Waypoint]) -> Any:
    """
    Sum the science points collected at the selected stops.

    Args:
        route: list of Waypoint

    Returns:
        total
    """
    total = 0
    for stop in route:
        total = total + stop.science
    return total


def payload_total(route: list[Waypoint]) -> Any:
    """
    Sum the sample mass that must fit in the rover's cargo bay.

    Args:
        route: list of Waypoint

    Returns:
        total
    """
    total = 0
    for stop in route:
        total = total + stop.sample_kg
    return total


def sampling_hours(route: list[Waypoint]) -> Any:
    """
    Sum the time spent collecting samples rather than driving.

    Args:
        route: list of Waypoint

    Returns:
        total
    """
    total = 0
    for stop in route:
        total = total + stop.dwell_hours
    return total


def pace_factor(pace: str) -> Any:
    """
    Trade energy efficiency for travel speed.

    Args:
        pace: string

    Returns:
        factor
    """
    if not (pace in ["Eco", "Traverse", "Sprint"]):
        raise ValueError('Choose Eco, Traverse, or Sprint')
    if pace == "Sprint":
        fast_factor = 1.35
    else:
        fast_factor = 1
    if pace == "Eco":
        factor = 0.85
    else:
        factor = fast_factor
    return factor


def travel_speed(pace: str) -> Any:
    """
    Map the selected driving mode to kilometers per hour.

    Args:
        pace: string

    Returns:
        speed
    """
    if not (pace in ["Eco", "Traverse", "Sprint"]):
        raise ValueError('Choose Eco, Traverse, or Sprint')
    if pace == "Sprint":
        fast_speed = 12
    else:
        fast_speed = 9
    if pace == "Eco":
        speed = 6
    else:
        speed = fast_speed
    return speed


def weather_factor(weather: str) -> Any:
    """
    Increase driving energy demand under dust and storm conditions.

    Args:
        weather: string

    Returns:
        factor
    """
    if not (weather in ["Clear", "Dust", "Storm"]):
        raise ValueError('Choose Clear, Dust, or Storm')
    if weather == "Storm":
        storm_factor = 1.6
    else:
        storm_factor = 1.25
    if weather == "Clear":
        factor = 1
    else:
        factor = storm_factor
    return factor


def energy_needed(distance: float, payload: float, sampling: float, rover: Rover) -> float:
    """
    Budget driving with the full planned payload on every leg, plus sampling at 3 kW.

    Args:
        distance: number
        payload: number
        sampling: number
        rover: Rover

    Returns:
        driving + sampling * 3
    """
    if not (distance >= 0):
        raise ValueError('Distance cannot be negative')
    if not (payload >= 0):
        raise ValueError('Payload cannot be negative')
    if not (sampling >= 0):
        raise ValueError('Sampling time cannot be negative')
    consumption = 1.2 + payload * 0.015
    driving = distance * consumption * pace_factor(rover.pace) * weather_factor(rover.weather)
    return driving + sampling * 3


def mission_hours(distance: float, sampling: float, pace: str) -> Any:
    """
    Combine driving time with sample collection time.

    Args:
        distance: number
        sampling: number
        pace: string

    Returns:
        distance / [travel-speed](pace) + sampling
    """
    return distance / travel_speed(pace) + sampling


def reserve_energy(rover: Rover) -> float:
    """
    Protect the operator's chosen fraction of the battery from mission use.

    Args:
        rover: Rover

    Returns:
        rover.battery * rover.reserve_percent / 100
    """
    return rover.battery * rover.reserve_percent / 100


def readiness_label(stops: float, energy_margin: float, payload_margin: float) -> Any:
    """
    Explain the first unmet launch condition in a stable order.

    Args:
        stops: number
        energy_margin: number
        payload_margin: number

    Returns:
        status
    """
    if payload_margin < 0:
        cargo_status = "OVER CAPACITY"
    else:
        cargo_status = "READY TO EXPLORE"
    if energy_margin < 0:
        power_status = "LOW POWER"
    else:
        power_status = cargo_status
    if stops == 0:
        status = "AWAITING ROUTE"
    else:
        status = power_status
    return status


def assess_mission(route: list[Waypoint], rover: Rover) -> Any:
    """
    Turn a proposed route and rover configuration into an auditable launch decision.

    Args:
        route: list of Waypoint
        rover: Rover

    Returns:
        Readiness(status, can_launch, distance, [mission-hours](distance, sampling, rover.pace), energy, remaining, reserve, energy_margin, payload, payload_margin, [science-total](route))
    """
    if not (len(route) <= 6):
        raise ValueError('A mission supports at most six stops')
    distance = route_distance(route, base())
    payload = payload_total(route)
    sampling = sampling_hours(route)
    energy = energy_needed(distance, payload, sampling, rover)
    reserve = reserve_energy(rover)
    remaining = rover.battery - energy
    energy_margin = remaining - reserve
    payload_margin = rover.payload_limit - payload
    can_launch = len(route) > 0 and energy_margin >= 0 and payload_margin >= 0
    status = readiness_label(len(route), energy_margin, payload_margin)
    return Readiness(status, can_launch, distance, mission_hours(distance, sampling, rover.pace), energy, remaining, reserve, energy_margin, payload, payload_margin, science_total(route))


def authorize_launch(route: list[Waypoint], report: Readiness) -> Readiness:
    """
    Refuse launch when the route, energy reserve, or sample capacity contract fails.

    Args:
        route: list of Waypoint
        report: Readiness

    Returns:
        report
    """
    if not (len(route) > 0):
        __nls_error = ValueError('Choose at least one survey site before launch')
        __nls_error.code = 'NO_ROUTE'
        raise __nls_error
    if not (report.energy_margin >= 0):
        __nls_error = ValueError('This route would consume the protected energy reserve')
        __nls_error.code = 'POWER_RESERVE'
        raise __nls_error
    if not (report.payload_margin >= 0):
        __nls_error = ValueError('The planned samples exceed the cargo capacity')
        __nls_error.code = 'PAYLOAD_LIMIT'
        raise __nls_error
    return report


def make_leg(origin: Waypoint, destination: Waypoint, payload: float, rover: Rover) -> Any:
    """
    Describe one travel segment using the same energy and time rules as the planner.

    Args:
        origin: Waypoint
        destination: Waypoint
        payload: number
        rover: Rover

    Returns:
        Leg(destination.name, destination.code, destination.x, destination.y, distance, energy, hours, destination.science)
    """
    distance = distance_between(origin, destination)
    energy = energy_needed(distance, payload, destination.dwell_hours, rover)
    hours = mission_hours(distance, destination.dwell_hours, rover.pace)
    return Leg(destination.name, destination.code, destination.x, destination.y, distance, energy, hours, destination.science)


def build_legs(route: list[Waypoint], origin: Waypoint, payload: float, rover: Rover, cursor: Optional[float] = None) -> Any:
    """
    Recursively create a flight manifest ending safely at Aster Base.

    Args:
        route: list of Waypoint
        origin: Waypoint
        payload: number
        rover: Rover
        cursor: number

    Returns:
        legs
    """
    if cursor is not None:
        index = cursor
    else:
        index = 0
    if index >= len(route):
        legs = [make_leg(origin, base(), payload, rover)]
    else:
        legs = [make_leg(origin, route[index], payload, rover)] + build_legs(route, route[index], payload, rover, index + 1)
    return legs


def clamp_percent(value: float) -> float:
    """
    Keep display percentages within a valid progress range.

    Args:
        value: number

    Returns:
        min(100, max(0, value))
    """
    return min(100, max(0, value))


# --- Literal blocks ---
import json
import os
import sys
from dataclasses import asdict
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import urlsplit

ASSET_ROOT = next(
    (Path(p) for p in [str(Path(__file__).parent), *sys.path]
     if p and (Path(p) / "mission_control.nl").is_file()
     and (Path(p) / "web.html").is_file()),
    Path(__file__).parent,
)

def evaluate_request(data, launch=False):
    """Validate transport types, then call compiled NLS constructors and rules."""
    if not isinstance(data, dict):
        raise ValueError("Expected a JSON object")
    codes = data.get("route", [])
    if not isinstance(codes, list) or any(not isinstance(code, str) for code in codes):
        raise ValueError("Route must be a list of site codes")
    available = {site.code: site for site in catalog()}
    if len(codes) > 6 or len(set(codes)) != len(codes):
        raise ValueError("Choose each site at most once, up to six stops")
    if any(code not in available for code in codes):
        raise ValueError("Route contains an unknown survey site")
    numeric = {}
    for key, default in [("battery", 160), ("reserve_percent", 20), ("payload_limit", 45)]:
        value = data.get(key, default)
        if type(value) not in (int, float) or not math.isfinite(value):
            raise ValueError(key + " must be a finite number")
        numeric[key] = value
    rover = Rover(**numeric, pace=data.get("pace", "Traverse"), weather=data.get("weather", "Clear"))
    route = [available[code] for code in codes]
    report = assess_mission(route, rover)
    if launch:
        authorize_launch(route, report)
    legs = build_legs(route, base(), report.payload, rover) if route else []
    return {"report": asdict(report), "energy_percent": clamp_percent(report.energy / rover.battery * 100),
            "legs": [asdict(leg) for leg in legs],
            "route": [asdict(site) for site in route], "rover": asdict(rover)}

class MissionHandler(BaseHTTPRequestHandler):
    def log_message(self, format, *args):
        pass

    def reply(self, status, body, content_type="application/json; charset=utf-8"):
        if not isinstance(body, bytes):
            body = json.dumps(body, allow_nan=False).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.send_header("X-Content-Type-Options", "nosniff")
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self):
        path = urlsplit(self.path).path
        if path == "/":
            self.reply(200, (ASSET_ROOT / "web.html").read_bytes(), "text/html; charset=utf-8")
        elif path == "/api/catalog":
            self.reply(200, {"waypoints": [asdict(site) for site in catalog()], "base": asdict(base())})
        elif path == "/api/source":
            self.reply(200, (ASSET_ROOT / "mission_control.nl").read_bytes(), "text/plain; charset=utf-8")
        elif path == "/favicon.ico":
            self.reply(204, b"")
        else:
            self.reply(404, {"error": "Not found"})

    def do_POST(self):
        path = urlsplit(self.path).path
        if path not in ("/api/evaluate", "/api/launch"):
            self.reply(404, {"error": "Not found"})
            return
        try:
            length = int(self.headers.get("Content-Length", "0"))
            if not 0 < length <= 16384:
                raise ValueError("Expected a JSON request smaller than 16 KB")
            data = json.loads(self.rfile.read(length))
            result = evaluate_request(data, launch=path == "/api/launch")
            self.reply(200, result)
        except (ValueError, TypeError, KeyError, OverflowError) as error:
            code = getattr(error, "code", "INVALID_PLAN")
            self.reply(400 if code == "INVALID_PLAN" else 422, {"error": str(error), "code": code})

def create_server(port=8765):
    """Bind only to the local computer. Port zero is useful for smoke tests."""
    return ThreadingHTTPServer(("127.0.0.1", port), MissionHandler)

def serve_showcase():
    port = int(os.environ.get("ASTER_PORT", "8765"))
    with create_server(port) as server:
        print("Aster Mission Control: http://127.0.0.1:" + str(server.server_port), flush=True)
        print("Local fictional rover simulation. Press Ctrl+C to stop.", flush=True)
        try:
            server.serve_forever()
        except KeyboardInterrupt:
            pass


if __name__ == '__main__':
    serve_showcase()