"""
Tests generated by nlsc from examples/showcase/mission_control.nl
"""

import pytest
from .mission_control import *


class TestDistance_Between:
    def test_case_1(self):
        assert distance_between(base(), Waypoint("t", "Test", 3, 4, 0, 0, 0)) == 5

    def test_case_2(self):
        assert distance_between(base(), base()) == 0


class TestRoute_Distance:
    def test_case_1(self):
        assert route_distance([], base()) == 0

    def test_case_2(self):
        assert route_distance([Waypoint("t", "Test", 3, 4, 0, 0, 0)], base()) == 10


class TestScience_Total:
    def test_case_1(self):
        assert science_total([]) == 0

    def test_case_2(self):
        assert science_total(catalog()) == 204


class TestPayload_Total:
    def test_case_1(self):
        assert payload_total([]) == 0

    def test_case_2(self):
        assert payload_total(catalog()) == 48


class TestSampling_Hours:
    def test_case_1(self):
        assert sampling_hours([]) == 0

    def test_case_2(self):
        assert sampling_hours([Waypoint("t", "Test", 0, 0, 0, 0, 2)]) == 2


class TestPace_Factor:
    def test_case_1(self):
        assert pace_factor("Eco") == 0.85

    def test_case_2(self):
        assert pace_factor("Traverse") == 1

    def test_case_3(self):
        assert pace_factor("Sprint") == 1.35


class TestWeather_Factor:
    def test_case_1(self):
        assert weather_factor("Clear") == 1

    def test_case_2(self):
        assert weather_factor("Dust") == 1.25

    def test_case_3(self):
        assert weather_factor("Storm") == 1.6


class TestEnergy_Needed:
    def test_case_1(self):
        assert energy_needed(10, 0, 1, Rover(160, 20, 45, "Traverse", "Clear")) == 15

    def test_case_2(self):
        assert energy_needed(0, 0, 0, Rover(160, 20, 45, "Eco", "Storm")) == 0


class TestMission_Hours:
    def test_case_1(self):
        assert mission_hours(12, 1, "Eco") == 3

    def test_case_2(self):
        assert mission_hours(12, 1, "Sprint") == 2


class TestReserve_Energy:
    def test_case_1(self):
        assert reserve_energy(Rover(160, 20, 45, "Traverse", "Clear")) == 32

    def test_case_2(self):
        assert reserve_energy(Rover(100, 40, 45, "Traverse", "Clear")) == 40


class TestReadiness_Label:
    def test_case_1(self):
        assert readiness_label(0, 10, 10) == "AWAITING ROUTE"

    def test_case_2(self):
        assert readiness_label(1, -1, 10) == "LOW POWER"

    def test_case_3(self):
        assert readiness_label(1, 10, -1) == "OVER CAPACITY"

    def test_case_4(self):
        assert readiness_label(1, 0, 0) == "READY TO EXPLORE"


class TestAssess_Mission:
    def test_case_1(self):
        assert assess_mission([], Rover(160, 20, 45, "Traverse", "Clear")).can_launch == False

    def test_case_2(self):
        assert assess_mission([], Rover(160, 20, 45, "Traverse", "Clear")).remaining == 160

    def test_case_3(self):
        assert assess_mission([Waypoint("t", "Test", 3, 4, 10, 2, 1)], Rover(160, 20, 45, "Traverse", "Clear")).can_launch == True

    def test_case_4(self):
        assert assess_mission(catalog(), Rover(240, 20, 5, "Eco", "Clear")).can_launch == False


class TestBuild_Legs:
    def test_case_1(self):
        assert len(build_legs([Waypoint("t", "Test", 3, 4, 10, 2, 1)], base(), 2, Rover(160, 20, 45, "Traverse", "Clear"))) == 2

    def test_case_2(self):
        assert build_legs([], base(), 0, Rover(160, 20, 45, "Traverse", "Clear"))[0].destination == "Aster Base"


class TestClamp_Percent:
    def test_case_1(self):
        assert clamp_percent(-10) == 0

    def test_case_2(self):
        assert clamp_percent(150) == 100

    def test_case_3(self):
        assert clamp_percent(42) == 42
