"""
Generated by nlsc from examples/text-rpg/src/combat.nl
Module: combat
"""

from dataclasses import dataclass

from .entities import *


@dataclass
class CombatResult:
    damage: float
    is_critical: bool
    target_dead: bool
    message: str


def attack(attacker: Entity, target: Entity) -> CombatResult:
    """
    Perform an attack action between two entities

    Args:
        attacker: Entity
        target: Entity

    Returns:
        CombatResult(damage, is_critical, is_dead, msg)
    """
    if not (attacker.hp > 0):
        raise ValueError('Dead entities cannot attack')
    if not (target.hp > 0):
        raise ValueError('Target is already dead')
    damage = attacker.attack - target.defense
    is_critical = damage > 10
    if is_critical:
        damage = damage * 2
    if damage < 1:
        damage = 1
    target.hp = target.hp - damage
    is_dead = target.hp <= 0
    msg = "Hit for " + str(damage)
    if is_critical:
        msg = msg + " (CRITICAL!)"
    if is_dead:
        msg = msg + " - Target slain!"
    return CombatResult(damage, is_critical, is_dead, msg)
