"""
Generated by nlsc from examples/text-rpg/src/entities.nl
Module: entities
"""

from dataclasses import dataclass


@dataclass
class Entity:
    name: str
    hp: float
    max_hp: float
    attack: float
    defense: float


def create_hero(name: str) -> Entity:
    """
    Initialize a new hero with starting stats

    Args:
        name: string

    Returns:
        Entity(name, 100, 100, 15, 5)
    """
    return Entity(name, 100, 100, 15, 5)


def create_monster(name: str, difficulty: float) -> Entity:
    """
    Initialize a new monster

    Args:
        name: string
        difficulty: number

    Returns:
        Entity(name, hp, hp, atk, 0)
    """
    hp = 20 * difficulty
    atk = 3 * difficulty
    return Entity(name, hp, hp, atk, 0)
