"""
Generated by nlsc from examples/text-rpg/src/game.nl
Module: game
"""

from dataclasses import dataclass

from .entities import *
from .combat import *


@dataclass
class RoundResult:
    over: bool
    status: str
    hero_msg: str
    monster_msg: str


def execute_round(hero: Entity, monster: Entity, round_num: float) -> RoundResult:
    """
    Execute one round of combat (Hero attack then Monster attack)

    Args:
        hero: Entity
        monster: Entity
        round_num: number

    Returns:
        RoundResult(is_game_over, status, hero_result.message, monster_msg)
    """
    hero_result = attack(hero, monster)
    is_game_over = hero_result.target_dead
    monster_msg = ""
    if not is_game_over:
        monster_msg = attack(monster, hero).message
    if not is_game_over:
        is_game_over = hero.hp <= 0
    status = "Round " + str(round_num) + " complete."
    if hero_result.target_dead:
        status = "VICTORY! " + monster.name + " defeated."
    if hero.hp <= 0:
        status = "DEFEAT! " + hero.name + " died."
    return RoundResult(is_game_over, status, hero_result.message, monster_msg)



if __name__ == '__main__':
    print("=== NLS TEXT RPG ===")
    print("Initializing from compiled .nl files...")
    hero = create_hero("Gandalf")
    monster = create_monster("Goblin", 1)
    print(hero)
    print(monster)
    print("BATTLE START!")
    round_num = 1
    while hero.hp > 0 and monster.hp > 0:
        result = execute_round(hero, monster, round_num)
        print(result.hero_msg)
        print(result.monster_msg)
        print(result.status)
        round_num = round_num + 1