"""
Generated by nlsc from examples/billing.nl
Module: billing
"""

from dataclasses import dataclass
from typing import Any


@dataclass
class LineItem:
    description: str
    quantity: float
    unit_price: float

    def __post_init__(self):
        if not self.description:
            raise ValueError('description is required')


@dataclass
class Invoice:
    id: str
    customer_name: str
    items: list[LineItem]
    tax_rate: float
    discount_percent: float

    def __post_init__(self):
        if not self.id:
            raise ValueError('id is required')
        if not self.customer_name:
            raise ValueError('customer_name is required')
        if not (self.tax_rate >= 0):
            raise ValueError("Invariant violated: tax_rate >= 0")
        if not (self.tax_rate <= 100):
            raise ValueError("Invariant violated: tax_rate <= 100")
        if not (self.discount_percent >= 0):
            raise ValueError("Invariant violated: discount_percent >= 0")
        if not (self.discount_percent <= 100):
            raise ValueError("Invariant violated: discount_percent <= 100")


def calculate_line_total(item: LineItem) -> float:
    """
    Calculate the total for a single line item.

    Args:
        item: LineItem

    Returns:
        item.quantity * item.unit_price
    """
    return item.quantity * item.unit_price


def calculate_subtotal(invoice: Invoice) -> Any:
    """
    Sum all line item totals for an invoice.

    Args:
        invoice: Invoice

    Returns:
        sum(item.quantity * item.unit_price for item in invoice.items)
    """
    # Sum each item's total -> subtotal
    return sum(item.quantity * item.unit_price for item in invoice.items)


def apply_discount(amount: float, discount_percent: float) -> Any:
    """
    Apply a percentage discount to an amount.

    Args:
        amount: number
        discount_percent: number

    Returns:
        amount * (1 - discount_percent / 100)
    """
    if not (discount_percent >= 0):
        raise ValueError('Discount cannot be negative')
    if not (discount_percent <= 100):
        raise ValueError('Discount cannot exceed 100%')
    # Calculate discount amount -> discount
    # Subtract from original -> final
    return amount * (1 - discount_percent / 100)


def calculate_tax(amount: float, tax_rate: float) -> Any:
    """
    Calculate tax on a given amount.

    Args:
        amount: number
        tax_rate: number

    Returns:
        amount * (tax_rate / 100)
    """
    if not (tax_rate >= 0):
        raise ValueError('Tax rate cannot be negative')
    return amount * (tax_rate / 100)


def calculate_invoice_total(invoice: Invoice) -> Any:
    """
    Calculate the final total for an invoice including tax and discount.

    Args:
        invoice: Invoice

    Returns:
        calculate_subtotal(invoice) * (1 - invoice.discount_percent / 100) * (1 + invoice.tax_rate / 100)
    """
    # Calculate subtotal from all items -> subtotal
    # Apply discount to subtotal -> discounted
    # Calculate tax on discounted amount -> tax
    # Add tax to discounted amount -> total
    return calculate_subtotal(invoice) * (1 - invoice.discount_percent / 100) * (1 + invoice.tax_rate / 100)
