"""
Generated by nlsc from examples/math.nl
Module: math
"""


def add(a: float, b: float) -> float:
    """
    Add two numbers

    Args:
        a: number
        b: number

    Returns:
        a + b
    """
    return a + b


def multiply(a: float, b: float) -> float:
    """
    Multiply two numbers

    Args:
        a: number
        b: number

    Returns:
        a × b
    """
    return a * b
