"""
Generated by nlsc from examples/shop_demo.nl
Module: shop_demo
"""

from typing import Any


def divide(numerator: float, divisor: float) -> float:
    """
    Divide two numbers safely.

    Args:
        numerator: number
        divisor: number

    Returns:
        numerator / divisor
    """
    if not (divisor != 0):
        raise ValueError('Cannot divide by zero')
    result = numerator / divisor
    return numerator / divisor


def calculate_discount(price: float, discount_percent: float) -> Any:
    """
    Calculate a discounted final price.

    Args:
        price: number
        discount_percent: number

    Returns:
        price - price * (discount_percent / 100)
    """
    if not (discount_percent >= 0):
        raise ValueError('discount_percent must be >= 0')
    if not (discount_percent <= 100):
        raise ValueError('discount_percent must be <= 100')
    discount_amount = price * (discount_percent / 100)
    final_price = price - discount_amount
    return price - price * (discount_percent / 100)
