/**
 * Generated by nlsc from examples/sorting_ts.nl
 * Module: sorting_ts
 */

/**
 * Sort a list of numbers using the quicksort algorithm
 * @param items list of number
 * @returns sorted_lesser + equal + sorted_greater
 */
export function quick_sort(items: number[]): number[] {
  if (items.length < 2) {
    return items;
  }
  const pivot = items[0];
  const lesser = items.filter((x) => x < pivot);
  const equal = items.filter((x) => x === pivot);
  const greater = items.filter((x) => x > pivot);
  const sorted_lesser = quick_sort(lesser);
  const sorted_greater = quick_sort(greater);
  return [...sorted_lesser, ...equal, ...sorted_greater];
}
