"""
Generated by nlsc from examples/sorting.nl
Module: sorting
"""

from __future__ import annotations


def quick_sort(items: list[float]) -> list[float]:
    """
    Sort a list of numbers using the quicksort algorithm

    Args:
        items: list of number

    Returns:
        sorted_lesser + equal + sorted_greater
    """
    if len(items) < 2:
        return items
    pivot = items[0]
    lesser = [x for x in items if x < pivot]
    equal = [x for x in items if x == pivot]
    greater = [x for x in items if x > pivot]
    sorted_lesser = quick_sort(lesser)
    sorted_greater = quick_sort(greater)
    return sorted_lesser + equal + sorted_greater
