/**
 * Generated by nlsc from examples/sorting_ts.nl
 * Module: sorting_ts
 */

// NLS runtime helpers: structural equality, NLS truthiness, and
// Python-compatible division/modulo semantics (#202).
function __nls_eq(a: any, b: any): boolean {
  if (a === b) { return true; }
  if (typeof a === "number" && typeof b === "number") {
    return Number.isNaN(a) && Number.isNaN(b);
  }
  if (Array.isArray(a) && Array.isArray(b)) {
    if (a.length !== b.length) { return false; }
    for (let i = 0; i < a.length; i++) {
      if (!__nls_eq(a[i], b[i])) { return false; }
    }
    return true;
  }
  if (a !== null && b !== null && typeof a === "object" && typeof b === "object") {
    const ka = Object.keys(a as object);
    const kb = Object.keys(b as object);
    if (ka.length !== kb.length) { return false; }
    for (const k of ka) {
      if (!__nls_eq((a as any)[k], (b as any)[k])) { return false; }
    }
    return true;
  }
  return false;
}
function __nls_truthy(v: any): boolean {
  if (v === null || v === undefined) { return false; }
  if (Array.isArray(v)) { return v.length > 0; }
  if (typeof v === "string") { return v.length > 0; }
  return Boolean(v);
}
class ZeroDivisionError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "ZeroDivisionError";
  }
}
function __nls_div(a: number, b: number): number {
  if (b === 0) { throw new ZeroDivisionError("division by zero"); }
  return a / b;
}
function __nls_floor_div(a: number, b: number): number {
  if (b === 0) { throw new ZeroDivisionError("integer division or modulo by zero"); }
  return Math.floor(a / b);
}
function __nls_mod(a: number, b: number): number {
  if (b === 0) { throw new ZeroDivisionError("integer division or modulo by zero"); }
  return ((a % b) + b) % b;
}
function __nls_len(v: any): number {
  if (Array.isArray(v) || typeof v === "string") { return v.length; }
  if (v !== null && typeof v === "object") { return Object.keys(v).length; }
  throw new TypeError("object of no length");
}
function __nls_sum(items: any): number {
  return (items as any[]).reduce((acc: number, item: any) => acc + item, 0);
}
function __nls_max(...args: any[]): any {
  const items = args.length === 1 && Array.isArray(args[0]) ? args[0] : args;
  return items.reduce((best: any, item: any) => (item > best ? item : best));
}
function __nls_min(...args: any[]): any {
  const items = args.length === 1 && Array.isArray(args[0]) ? args[0] : args;
  return items.reduce((best: any, item: any) => (item < best ? item : best));
}


/**
 * Sort a list of numbers using the quicksort algorithm
 * @param items list of number
 * @returns sorted_lesser + equal + sorted_greater
 */
export function quick_sort(items: number[]): number[] {
  if (__nls_truthy(__nls_len(items) < 2)) {
    return items;
  }
  const pivot = items[0];
  let lesser: any = [];
  for (const x of items) {
    if (!__nls_truthy(x < pivot)) { continue; }
    lesser = [...lesser, x];
  }
  let equal: any = [];
  for (const x of items) {
    if (!__nls_truthy(__nls_eq(x, pivot))) { continue; }
    equal = [...equal, x];
  }
  let greater: any = [];
  for (const x of items) {
    if (!__nls_truthy(x > pivot)) { continue; }
    greater = [...greater, x];
  }
  const sorted_lesser = quick_sort(lesser);
  const sorted_greater = quick_sort(greater);
  return [...sorted_lesser, ...equal, ...sorted_greater];
}
