"""
Generated by nlsc from examples/sorting.nl
Module: sorting
"""

from __future__ import annotations


def quick_sort(items: list[float]) -> list[float]:
    """
    Sort a list of numbers using the quicksort algorithm

    Args:
        items: list of number

    Returns:
        sorted_lesser + equal + sorted_greater
    """
    if len(items) < 2:
        return items
    pivot = items[0]
    lesser = []
    for x in items:
        if not (x < pivot):
            continue
        lesser = lesser + [x]
    equal = []
    for x in items:
        if not (x == pivot):
            continue
        equal = equal + [x]
    greater = []
    for x in items:
        if not (x > pivot):
            continue
        greater = greater + [x]
    sorted_lesser = quick_sort(lesser)
    sorted_greater = quick_sort(greater)
    return sorted_lesser + equal + sorted_greater
