"""
Generated by nlsc from examples/sorting_ja.nl
Module: sorting_ja
"""

from __future__ import annotations


def クイックソート(項目: list[float]) -> list[float]:
    """
    数値のリストをクイックソートで並べ替える

    Args:
        項目: list of number

    Returns:
        整列済みの小さい項目 + 等しい項目 + 整列済みの大きい項目
    """
    if len(項目) < 2:
        return 項目
    ピボット = 項目[0]
    小さい項目 = [要素 for 要素 in 項目 if 要素 < ピボット]
    等しい項目 = [要素 for 要素 in 項目 if 要素 == ピボット]
    大きい項目 = [要素 for 要素 in 項目 if 要素 > ピボット]
    整列済みの小さい項目 = クイックソート(小さい項目)
    整列済みの大きい項目 = クイックソート(大きい項目)
    return 整列済みの小さい項目 + 等しい項目 + 整列済みの大きい項目
