"""
Generated by nlsc from examples/strings.nl
Module: strings
"""

from typing import Any


def is_empty(text: str) -> Any:
    """
    Check if a string is empty or whitespace only

    Args:
        text: string

    Returns:
        not text or text.isspace()
    """
    return not text or text.isspace()


def truncate(text: str, max_length: float) -> Any:
    """
    Shorten text to a maximum length with ellipsis

    Args:
        text: string
        max_length: number

    Returns:
        text if len(text) <= max_length else text[:int(max_length) - 3] + "..."
    """
    if not (max_length >= 4):
        raise ValueError('max_length must be >= 4')
    return text if len(text) <= max_length else text[:int(max_length) - 3] + "..."


def slugify(text: str) -> Any:
    """
    Convert text to URL-friendly slug format

    Args:
        text: string

    Returns:
        '-'.join(filter(None, ''.join(c if c.isalnum() else '-' for c in text.lower().strip()).split('-')))
    """
    return '-'.join(filter(None, ''.join(c if c.isalnum() else '-' for c in text.lower().strip()).split('-')))


def title_case(text: str) -> Any:
    """
    Convert text to title case

    Args:
        text: string

    Returns:
        text.title()
    """
    return text.title()
