"""
Generated by nlsc from examples\strings.nl
Module: strings
"""


def is_empty(text: str) -> not text or text.isspace():
    """
    Check if a string is empty or whitespace only

    Args:
        text: string

    Returns:
        not text or text.isspace()
    """
    raise NotImplementedError('is-empty')


def truncate(text: str, max_length: float) -> :
    """
    Shorten text to a maximum length with ellipsis

    Args:
        text: string
        max_length: number
    """
    raise NotImplementedError('truncate')


def slugify(text: str) -> :
    """
    Convert text to URL-friendly slug format

    Args:
        text: string
    """
    raise NotImplementedError('slugify')


def title_case(text: str) -> text.title():
    """
    Convert text to title case

    Args:
        text: string

    Returns:
        text.title()
    """
    return text.title()


# --- Literal blocks ---
def truncate(text: str, max_length: int) -> str:
    """Shorten text to a maximum length with ellipsis."""
    if max_length < 4:
        raise ValueError("max_length must be >= 4")
    if len(text) <= max_length:
        return text
    return text[:max_length - 3] + "..."
import re

def slugify(text: str) -> str:
    """Convert text to URL-friendly slug format."""
    text = text.lower().strip()
    text = re.sub(r'\s+', '-', text)
    text = re.sub(r'[^a-z0-9-]', '', text)
    text = re.sub(r'-+', '-', text)
    return text.strip('-')