"""
Generated by nlsc from examples/strings.nl
Module: strings
"""

from __future__ import annotations

from typing import Any


def is_empty(text: str) -> float:
    """
    Check if a string is empty or whitespace only

    Args:
        text: string

    Returns:
        len(text.strip()) == 0
    """
    return len(text.strip()) == 0


def truncate(text: str, max_length: float) -> Any:
    """
    Shorten text to a maximum length with ellipsis

    Args:
        text: string
        max_length: number

    Returns:
        result
    """
    if not (max_length >= 4):
        raise ValueError('max_length must be >= 4')
    if len(text) <= max_length:
        result = text
    else:
        result = ellipsised(text, max_length)
    return result


def title_case(text: str) -> Any:
    """
    Convert text to title case

    Args:
        text: string

    Returns:
        text.title()
    """
    return text.title()


# --- Literal blocks ---
def slugify(text: str) -> str:
    """Convert text to URL-friendly slug format."""
    cleaned = "".join(c if c.isalnum() else "-" for c in text.lower().strip())
    while "--" in cleaned:
        cleaned = cleaned.replace("--", "-")
    return cleaned.strip("-")


def ellipsised(text: str, max_length: float) -> str:
    """Cut text to max_length characters, the last three being an ellipsis."""
    return text[: int(max_length) - 3] + "..."