"""
Tests generated by nlsc from examples/sorting_ja.nl
"""

import pytest
from .sorting_ja import *


class Testクイックソート:
    def test_case_1(self):
        assert クイックソート([3, 1, 4, 1, 5]) == [1, 1, 3, 4, 5]

    def test_case_2(self):
        assert クイックソート([]) == []

    def test_case_3(self):
        assert クイックソート([1]) == [1]

    def test_case_4(self):
        assert クイックソート([5, 4, 3, 2, 1]) == [1, 2, 3, 4, 5]
