"""
Tests generated by nlsc from examples/strings.nl
"""

import pytest
from .strings import *


class TestIs_Empty:
    def test_case_1(self):
        assert is_empty("") == True

    def test_case_2(self):
        assert is_empty("   ") == True

    def test_case_3(self):
        assert is_empty("hello") == False


class TestTruncate:
    def test_case_1(self):
        assert truncate("hello", 10) == "hello"

    def test_case_2(self):
        assert truncate("hello", 5) == "hello"

    def test_case_3(self):
        assert truncate("hello world", 8) == "hello..."


class TestTitle_Case:
    def test_case_1(self):
        assert title_case("hello world") == "Hello World"

    def test_case_2(self):
        assert title_case("") == ""
