"""
Tests generated by nlsc from examples/math.nl
"""

import pytest
from .math import *


class TestAdd:
    def test_case_1(self):
        assert add(2, 3) == 5

    def test_case_2(self):
        assert add(-1, 1) == 0

    def test_case_3(self):
        assert add(0, 0) == 0
