"""
Tests generated by nlsc from examples/arithmetic.nl
"""

import pytest
from .arithmetic import *


class TestAdd:
    def test_case_1(self):
        assert add(2, 3) == 5

    def test_case_2(self):
        assert add(-1, 1) == 0

    def test_case_3(self):
        assert add(0, 0) == 0


class TestMultiply:
    def test_case_1(self):
        assert multiply(3, 4) == 12

    def test_case_2(self):
        assert multiply(-2, 5) == -10

    def test_case_3(self):
        assert multiply(7, 0) == 0
