"""
Tests generated by nlsc from examples/billing.nl
"""

import pytest
from .billing import *


class TestCalculate_Line_Total:
    def test_case_1(self):
        assert calculate_line_total(LineItem(description="Widget", quantity=5, unit_price=10)) == 50

    def test_case_2(self):
        assert calculate_line_total(LineItem(description="Gadget", quantity=1, unit_price=99.99)) == 99.99


class TestApply_Discount:
    def test_case_1(self):
        assert apply_discount(100, 10) == 90

    def test_case_2(self):
        assert apply_discount(100, 0) == 100

    def test_case_3(self):
        assert apply_discount(100, 100) == 0

    def test_case_4(self):
        assert apply_discount(50, 25) == 37.5


class TestCalculate_Tax:
    def test_case_1(self):
        assert calculate_tax(100, 10) == 10

    def test_case_2(self):
        assert calculate_tax(100, 0) == 0

    def test_case_3(self):
        assert calculate_tax(200, 7.5) == 15
