"""
Tests generated by nlsc from examples/sorting.nl
"""

import pytest
from .sorting import *


class TestQuick_Sort:
    def test_case_1(self):
        assert quick_sort([3, 1, 4, 1, 5]) == [1, 1, 3, 4, 5]

    def test_case_2(self):
        assert quick_sort([]) == []

    def test_case_3(self):
        assert quick_sort([1]) == [1]

    def test_case_4(self):
        assert quick_sort([5, 4, 3, 2, 1]) == [1, 2, 3, 4, 5]
