"""
Tests generated by nlsc from examples/shop_demo.nl
"""

import pytest
from .shop_demo import *


class TestDivide:
    def test_case_1(self):
        assert divide(10, 2) == 5


class TestCalculate_Discount:
    def test_case_1(self):
        assert calculate_discount(100, 25) == 75

    def test_case_2(self):
        assert calculate_discount(50, 0) == 50

    def test_case_3(self):
        assert calculate_discount(80, 100) == 0
