"""
Generated by nlsc from examples/workflow_engine.nl
Module: workflow_engine
Status: INCOMPLETE SCAFFOLD - 65 ANLU(s) have unresolved executable content: activate-workflow, add-task-to-workflow, all-tasks-terminal, archive-workflow, assign-task-to-user, average-estimate, balance-workload, calculate-average-completion-time, calculate-completed-work, calculate-critical-path-length, calculate-estimate-std-dev, calculate-estimate-variance, calculate-estimation-accuracy, calculate-pert-estimate, calculate-remaining-work, calculate-task-hours, calculate-team-workload, calculate-total-hours, calculate-user-workload, calculate-velocity, calculate-workflow-metrics, calculate-workflow-progress, compare-priorities, complete-workflow, count-tasks-by-status, create-assignment, create-workflow, detect-circular-dependencies, estimate-completion-date, filter-overdue-tasks, filter-tasks-by-assignee, filter-tasks-by-priority, filter-tasks-by-status, filter-tasks-due-soon, filter-unassigned-tasks, find-least-loaded-user, find-most-loaded-user, generate-priority-summary, generate-status-summary, generate-user-performance-report, generate-workflow-summary, get-blocking-tasks, get-dependency-depth, get-highest-priority, get-overloaded-users, get-ready-tasks, get-status-counts, get-task-by-id, get-user-tasks, has-unmet-dependencies, is-task-actionable, is-workflow-on-track, pause-workflow, priority-to-weight, reassign-task, remove-task-from-workflow, resume-workflow, search-tasks-by-tag, search-tasks-by-title, sort-tasks-by-created-date, sort-tasks-by-due-date, sort-tasks-by-priority, sum-estimates, topological-sort-tasks, unassign-task
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, cast, Optional


@dataclass
class Priority:
    value: str

    def __post_init__(self):
        if not self.value:
            raise ValueError('value is required')


@dataclass
class TaskStatus:
    value: str

    def __post_init__(self):
        if not self.value:
            raise ValueError('value is required')


@dataclass
class WorkflowStatus:
    value: str

    def __post_init__(self):
        if not self.value:
            raise ValueError('value is required')


@dataclass
class User:
    id: str
    name: str
    email: str
    role: str
    capacity: float
    skills: list[str]

    def __post_init__(self):
        if not self.id:
            raise ValueError('id is required')
        if not self.name:
            raise ValueError('name is required')
        if not self.email:
            raise ValueError('email is required')
        if not self.role:
            raise ValueError('role is required')
        if self.capacity < 0:
            raise ValueError('capacity must be at least 0')
        if self.capacity > 100:
            raise ValueError('capacity must be at most 100')


@dataclass
class TimeEstimate:
    optimistic: float
    realistic: float
    pessimistic: float

    def __post_init__(self):
        if self.optimistic < 0:
            raise ValueError('optimistic must be at least 0')
        if self.realistic < 0:
            raise ValueError('realistic must be at least 0')
        if self.pessimistic < 0:
            raise ValueError('pessimistic must be at least 0')
        if not (self.optimistic <= self.realistic):
            raise ValueError("Invariant violated: optimistic <= realistic")
        if not (self.realistic <= self.pessimistic):
            raise ValueError("Invariant violated: realistic <= pessimistic")
        if not (self.pessimistic > 0):
            raise ValueError("Invariant violated: pessimistic > 0")


@dataclass
class Task:
    id: str
    title: str
    description: str
    status: TaskStatus
    priority: Priority
    created_at: float
    actual_hours: float
    dependencies: list[str]
    tags: list[str]
    assignee_id: Optional[str] = None
    due_date: Optional[float] = None
    completed_at: Optional[float] = None
    estimate: Optional[TimeEstimate] = None

    def __post_init__(self):
        if not self.id:
            raise ValueError('id is required')
        if not self.title:
            raise ValueError('title is required')
        if not self.status:
            raise ValueError('status is required')
        if not self.priority:
            raise ValueError('priority is required')
        if not self.created_at:
            raise ValueError('created_at is required')
        if self.actual_hours < 0:
            raise ValueError('actual_hours must be at least 0')
        if not (self.actual_hours >= 0):
            raise ValueError("Invariant violated: actual_hours >= 0")


@dataclass
class Workflow:
    id: str
    name: str
    description: str
    status: WorkflowStatus
    owner_id: str
    tasks: list[Task]
    created_at: float
    started_at: Optional[float] = None
    completed_at: Optional[float] = None
    deadline: Optional[float] = None

    def __post_init__(self):
        if not self.id:
            raise ValueError('id is required')
        if not self.name:
            raise ValueError('name is required')
        if not self.status:
            raise ValueError('status is required')
        if not self.owner_id:
            raise ValueError('owner_id is required')
        if not self.created_at:
            raise ValueError('created_at is required')


@dataclass
class Assignment:
    task_id: str
    user_id: str
    assigned_at: float
    assigned_by: str
    notes: Optional[str] = None

    def __post_init__(self):
        if not self.task_id:
            raise ValueError('task_id is required')
        if not self.user_id:
            raise ValueError('user_id is required')
        if not self.assigned_at:
            raise ValueError('assigned_at is required')
        if not self.assigned_by:
            raise ValueError('assigned_by is required')


@dataclass
class WorkloadReport:
    user_id: str
    total_tasks: float
    pending_tasks: float
    in_progress_tasks: float
    completed_tasks: float
    total_estimated_hours: float
    utilization_percent: float

    def __post_init__(self):
        if not self.user_id:
            raise ValueError('user_id is required')
        if self.total_tasks < 0:
            raise ValueError('total_tasks must be at least 0')
        if self.pending_tasks < 0:
            raise ValueError('pending_tasks must be at least 0')
        if self.in_progress_tasks < 0:
            raise ValueError('in_progress_tasks must be at least 0')
        if self.completed_tasks < 0:
            raise ValueError('completed_tasks must be at least 0')
        if self.total_estimated_hours < 0:
            raise ValueError('total_estimated_hours must be at least 0')
        if self.utilization_percent < 0:
            raise ValueError('utilization_percent must be at least 0')
        if self.utilization_percent > 100:
            raise ValueError('utilization_percent must be at most 100')
        if not (self.utilization_percent >= 0):
            raise ValueError("Invariant violated: utilization_percent >= 0")
        if not (self.utilization_percent <= 100):
            raise ValueError("Invariant violated: utilization_percent <= 100")


@dataclass
class WorkflowMetrics:
    workflow_id: str
    total_tasks: float
    completed_tasks: float
    blocked_tasks: float
    completion_percent: float
    is_on_track: bool
    critical_path_length: float
    estimated_completion_date: Optional[float] = None

    def __post_init__(self):
        if not self.workflow_id:
            raise ValueError('workflow_id is required')
        if self.total_tasks < 0:
            raise ValueError('total_tasks must be at least 0')
        if self.completed_tasks < 0:
            raise ValueError('completed_tasks must be at least 0')
        if self.blocked_tasks < 0:
            raise ValueError('blocked_tasks must be at least 0')
        if self.completion_percent < 0:
            raise ValueError('completion_percent must be at least 0')
        if self.completion_percent > 100:
            raise ValueError('completion_percent must be at most 100')
        if self.critical_path_length < 0:
            raise ValueError('critical_path_length must be at least 0')


@dataclass
class StatusCounts:
    pending: float
    in_progress: float
    blocked: float
    completed: float
    cancelled: float

    def __post_init__(self):
        if self.pending < 0:
            raise ValueError('pending must be at least 0')
        if self.in_progress < 0:
            raise ValueError('in_progress must be at least 0')
        if self.blocked < 0:
            raise ValueError('blocked must be at least 0')
        if self.completed < 0:
            raise ValueError('completed must be at least 0')
        if self.cancelled < 0:
            raise ValueError('cancelled must be at least 0')


@dataclass
class PriorityCounts:
    critical: float
    high: float
    medium: float
    low: float

    def __post_init__(self):
        if self.critical < 0:
            raise ValueError('critical must be at least 0')
        if self.high < 0:
            raise ValueError('high must be at least 0')
        if self.medium < 0:
            raise ValueError('medium must be at least 0')
        if self.low < 0:
            raise ValueError('low must be at least 0')


@dataclass
class ReassignmentSuggestion:
    task_id: str
    from_user_id: str
    to_user_id: str
    reason: str

    def __post_init__(self):
        if not self.task_id:
            raise ValueError('task_id is required')
        if not self.from_user_id:
            raise ValueError('from_user_id is required')
        if not self.to_user_id:
            raise ValueError('to_user_id is required')


def priority_to_weight(priority: Priority) -> Any:
    """
    Convert priority to numeric weight for sorting.

    Args:
        priority: Priority

    Returns:
        {"critical": 4, "high": 3, "medium": 2, "low": 1}.get(priority.value, 0)
    """
    weight = None  # TODO: Map critical to 4, high to 3, medium to 2, low to 1
    return {"critical": 4, "high": 3, "medium": 2, "low": 1}.get(priority.value, 0)


def compare_priorities(a: Priority, b: Priority) -> Any:
    """
    Compare two priorities, returning -1, 0, or 1.

    Args:
        a: Priority
        b: Priority

    Returns:
        (1 if priority_to_weight(a) > priority_to_weight(b) else (-1 if priority_to_weight(a) < priority_to_weight(b) else 0))
    """
    weight_a = None  # TODO: Get weight of a
    weight_b = None  # TODO: Get weight of b
    diff = None  # TODO: Calculate difference
    return (1 if priority_to_weight(a) > priority_to_weight(b) else (-1 if priority_to_weight(a) < priority_to_weight(b) else 0))


def get_highest_priority(tasks: list[Task]) -> float:
    """
    Get the highest priority from a list of tasks.

    Args:
        tasks: list of Task

    Returns:
        max(tasks, key=lambda t: priority_to_weight(t.priority)).priority
    """
    if not (len(tasks) > 0):
        raise ValueError('Cannot get priority from empty list')
    priorities = None  # TODO: Extract priorities from all tasks
    highest = None  # TODO: Find maximum by weight
    return max(tasks, key=lambda t: priority_to_weight(t.priority)).priority


def calculate_pert_estimate(estimate: TimeEstimate) -> Any:
    """
    Calculate PERT estimate using formula (O + 4M + P) / 6.

    Args:
        estimate: TimeEstimate

    Returns:
        (estimate.optimistic + 4 * estimate.realistic + estimate.pessimistic) / 6
    """
    if not (estimate.optimistic <= estimate.realistic):
        raise ValueError('Optimistic must be <= realistic')
    if not (estimate.realistic <= estimate.pessimistic):
        raise ValueError('Realistic must be <= pessimistic')
    pert = None  # TODO: Apply PERT formula
    return (estimate.optimistic + 4 * estimate.realistic + estimate.pessimistic) / 6


def calculate_estimate_variance(estimate: TimeEstimate) -> Any:
    """
    Calculate variance in time estimate for risk assessment.

    Args:
        estimate: TimeEstimate

    Returns:
        ((estimate.pessimistic - estimate.optimistic) / 6) ** 2
    """
    range_val = None  # TODO: Calculate range
    variance = None  # TODO: Divide by 6 and square
    return ((estimate.pessimistic - estimate.optimistic) / 6) ** 2


def calculate_estimate_std_dev(estimate: TimeEstimate) -> Any:
    """
    Calculate standard deviation of time estimate.

    Args:
        estimate: TimeEstimate

    Returns:
        calculate_estimate_variance(estimate) ** 0.5
    """
    var = None  # TODO: Calculate variance
    std_dev = None  # TODO: Take square root
    return calculate_estimate_variance(estimate) ** 0.5


def sum_estimates(estimates: list[TimeEstimate]) -> Any:
    """
    Sum multiple time estimates into one combined estimate.

    Args:
        estimates: list of TimeEstimate

    Returns:
        TimeEstimate(optimistic=sum(e.optimistic for e in estimates), realistic=sum(e.realistic for e in estimates), pessimistic=sum(e.pessimistic for e in estimates))
    """
    if not (len(estimates) > 0):
        raise ValueError('Cannot sum empty list of estimates')
    total_opt = None  # TODO: Sum all optimistic values
    total_real = None  # TODO: Sum all realistic values
    total_pess = None  # TODO: Sum all pessimistic values
    return TimeEstimate(optimistic=sum(e.optimistic for e in estimates), realistic=sum(e.realistic for e in estimates), pessimistic=sum(e.pessimistic for e in estimates))


def average_estimate(estimates: list[TimeEstimate]) -> Any:
    """
    Calculate average of multiple time estimates.

    Args:
        estimates: list of TimeEstimate

    Returns:
        TimeEstimate(optimistic=sum(e.optimistic for e in estimates) / len(estimates), realistic=sum(e.realistic for e in estimates) / len(estimates), pessimistic=sum(e.pessimistic for e in estimates) / len(estimates))
    """
    if not (len(estimates) > 0):
        raise ValueError('Cannot average empty list')
    total = None  # TODO: Sum all estimates
    avg = None  # TODO: Divide each component by count
    return TimeEstimate(optimistic=sum(e.optimistic for e in estimates) / len(estimates), realistic=sum(e.realistic for e in estimates) / len(estimates), pessimistic=sum(e.pessimistic for e in estimates) / len(estimates))


def is_task_actionable(task: Task) -> Any:
    """
    Check if a task can be worked on (not blocked or completed).

    Args:
        task: Task

    Returns:
        task.status.value in ["pending", "in_progress"]
    """
    actionable = None  # TODO: Check status is pending or in_progress
    return task.status.value in ["pending", "in_progress"]


def is_task_terminal(task: Task) -> Any:
    """
    Check if a task is in a terminal state.

    Args:
        task: Task

    Returns:
        task.status.value in ["completed", "cancelled"]
    """
    return task.status.value in ["completed", "cancelled"]


def is_task_blocked(task: Task) -> Any:
    """
    Check if a task has blocked status.

    Args:
        task: Task

    Returns:
        task.status.value == "blocked"
    """
    return task.status.value == "blocked"


def count_tasks_by_status(tasks: list[Task], status_value: str) -> float:
    """
    Count tasks matching a specific status.

    Args:
        tasks: list of Task
        status_value: string

    Returns:
        len([t for t in tasks if t.status.value == status_value])
    """
    matching = None  # TODO: Filter tasks to matching status
    count = None  # TODO: Count matching tasks
    return len([t for t in tasks if t.status.value == status_value])


def get_status_counts(tasks: list[Task]) -> Any:
    """
    Get counts of tasks by each status.

    Args:
        tasks: list of Task

    Returns:
        StatusCounts(pending=count_tasks_by_status(tasks, "pending"), in_progress=count_tasks_by_status(tasks, "in_progress"), blocked=count_tasks_by_status(tasks, "blocked"), completed=count_tasks_by_status(tasks, "completed"), cancelled=count_tasks_by_status(tasks, "cancelled"))
    """
    pending = None  # TODO: Count pending tasks
    in_progress = None  # TODO: Count in_progress tasks
    blocked = None  # TODO: Count blocked tasks
    completed = None  # TODO: Count completed tasks
    cancelled = None  # TODO: Count cancelled tasks
    return StatusCounts(pending=count_tasks_by_status(tasks, "pending"), in_progress=count_tasks_by_status(tasks, "in_progress"), blocked=count_tasks_by_status(tasks, "blocked"), completed=count_tasks_by_status(tasks, "completed"), cancelled=count_tasks_by_status(tasks, "cancelled"))


def get_task_by_id(tasks: list[Task], task_id: str) -> Any:
    """
    Find a task by its ID.

    Args:
        tasks: list of Task
        task_id: string

    Returns:
        next((t for t in tasks if t.id == task_id), None)
    """
    found = None  # TODO: Search for task with matching ID
    return next((t for t in tasks if t.id == task_id), None)


def get_blocking_tasks(task: Task, all_tasks: list[Task]) -> Any:
    """
    Get list of incomplete tasks that block a given task.

    Args:
        task: Task
        all_tasks: list of Task

    Returns:
        [t for t in all_tasks if t.id in task.dependencies and not is_task_terminal(t)]
    """
    dep_ids = None  # TODO: Get task IDs from dependencies
    deps = None  # TODO: Find tasks matching those IDs
    blocking = None  # TODO: Filter to non-terminal tasks
    return [t for t in all_tasks if t.id in task.dependencies and not is_task_terminal(t)]


def has_unmet_dependencies(task: Task, all_tasks: list[Task]) -> float:
    """
    Check if a task is blocked by incomplete dependencies.

    Args:
        task: Task
        all_tasks: list of Task

    Returns:
        len(get_blocking_tasks(task, all_tasks)) > 0
    """
    blockers = None  # TODO: Get blocking tasks
    blocked = None  # TODO: Check if any blockers exist
    return len(get_blocking_tasks(task, all_tasks)) > 0


def get_ready_tasks(tasks: list[Task]) -> Any:
    """
    Get all tasks that are ready to be worked on.

    Args:
        tasks: list of Task

    Returns:
        [t for t in tasks if is_task_actionable(t) and not has_unmet_dependencies(t, tasks)]
    """
    actionable = None  # TODO: Filter to actionable tasks
    ready = None  # TODO: Filter to those not blocked
    return [t for t in tasks if is_task_actionable(t) and not has_unmet_dependencies(t, tasks)]


def get_dependency_depth(task: Task, all_tasks: list[Task]) -> Any:
    """
    Calculate the maximum dependency chain depth for a task.

    Args:
        task: Task
        all_tasks: list of Task

    Returns:
        1 + max([get_dependency_depth(get_task_by_id(all_tasks, dep_id), all_tasks) for dep_id in task.dependencies if get_task_by_id(all_tasks, dep_id)], default=0)
    """
    deps = None  # TODO: Get direct dependencies
    depths = None  # TODO: Recursively calculate depth of each
    total_depth = None  # TODO: Return max depth plus 1
    return 1 + max([get_dependency_depth(get_task_by_id(all_tasks, dep_id), all_tasks) for dep_id in task.dependencies if get_task_by_id(all_tasks, dep_id)], default=0)


def detect_circular_dependencies(tasks: list[Task]) -> Any:
    """
    Detect if there are circular dependencies in task list.

    Args:
        tasks: list of Task

    Returns:
        any(t.id in [d for d in t.dependencies] for t in tasks)
    """
    adj = None  # TODO: Build adjacency list
    # Track visited and recursion stack -> visited, rec_stack
    has_cycle = None  # TODO: DFS from each unvisited node
    return any(t.id in [d for d in t.dependencies] for t in tasks)


def topological_sort_tasks(tasks: list[Task]) -> Any:
    """
    Sort tasks by dependency order.

    Args:
        tasks: list of Task

    Returns:
        sorted(tasks, key=lambda t: get_dependency_depth(t, tasks))
    """
    if not (not detect_circular_dependencies(tasks)):
        raise ValueError('Circular dependency detected')
    graph = None  # TODO: Build dependency graph
    roots = None  # TODO: Find tasks with no dependencies
    sorted_list = None  # TODO: Process queue, adding tasks when deps satisfied
    return sorted(tasks, key=lambda t: get_dependency_depth(t, tasks))


def create_assignment(task_id: str, user_id: str, assigner_id: str, timestamp: float, notes: Optional[str] = None) -> Any:
    """
    Create a new assignment record.

    Args:
        task_id: string
        user_id: string
        assigner_id: string
        timestamp: number
        notes: string

    Returns:
        Assignment(task_id=task_id, user_id=user_id, assigned_at=timestamp, assigned_by=assigner_id, notes=notes or "")
    """
    assignment = None  # TODO: Build assignment record
    return Assignment(task_id=task_id, user_id=user_id, assigned_at=timestamp, assigned_by=assigner_id, notes=notes or "")


def assign_task_to_user(task: Task, user: User, assigner_id: str, timestamp: float) -> Any:
    """
    Assign a task to a user.

    Args:
        task: Task
        user: User
        assigner_id: string
        timestamp: number

    Returns:
        (Task(id=task.id, title=task.title, description=task.description, status=task.status, priority=task.priority, assignee_id=user.id, created_at=task.created_at, due_date=task.due_date, completed_at=task.completed_at, estimate=task.estimate, actual_hours=task.actual_hours, dependencies=task.dependencies, tags=task.tags), create_assignment(task.id, user.id, assigner_id, timestamp))
    """
    if not (is_task_actionable(task)):
        raise ValueError('Cannot assign terminal task')
    if not (user.capacity > 0):
        raise ValueError('User has no available capacity')
    assignment = None  # TODO: Create assignment record
    updated_task = None  # TODO: Update task with assignee
    return (Task(id=task.id, title=task.title, description=task.description, status=task.status, priority=task.priority, assignee_id=user.id, created_at=task.created_at, due_date=task.due_date, completed_at=task.completed_at, estimate=task.estimate, actual_hours=task.actual_hours, dependencies=task.dependencies, tags=task.tags), create_assignment(task.id, user.id, assigner_id, timestamp))


def unassign_task(task: Task) -> Any:
    """
    Remove assignment from a task.

    Args:
        task: Task

    Returns:
        Task(id=task.id, title=task.title, description=task.description, status=task.status, priority=task.priority, assignee_id=None, created_at=task.created_at, due_date=task.due_date, completed_at=task.completed_at, estimate=task.estimate, actual_hours=task.actual_hours, dependencies=task.dependencies, tags=task.tags)
    """
    if not (task.assignee_id != None):
        raise ValueError('Task is not assigned')
    updated = None  # TODO: Clear assignee_id from task
    return Task(id=task.id, title=task.title, description=task.description, status=task.status, priority=task.priority, assignee_id=None, created_at=task.created_at, due_date=task.due_date, completed_at=task.completed_at, estimate=task.estimate, actual_hours=task.actual_hours, dependencies=task.dependencies, tags=task.tags)


def reassign_task(task: Task, new_user: User, assigner_id: str, timestamp: float) -> Any:
    """
    Reassign a task from one user to another.

    Args:
        task: Task
        new_user: User
        assigner_id: string
        timestamp: number

    Returns:
        assign_task_to_user(unassign_task(task), new_user, assigner_id, timestamp)
    """
    unassigned = None  # TODO: Unassign current user
    reassigned = None  # TODO: Assign to new user
    return assign_task_to_user(unassign_task(task), new_user, assigner_id, timestamp)


def get_user_tasks(tasks: list[Task], user_id: str) -> Any:
    """
    Get all tasks assigned to a user.

    Args:
        tasks: list of Task
        user_id: string

    Returns:
        [t for t in tasks if t.assignee_id == user_id]
    """
    user_tasks = None  # TODO: Filter tasks to user
    return [t for t in tasks if t.assignee_id == user_id]


def calculate_task_hours(task: Task) -> Any:
    """
    Calculate estimated hours for a single task.

    Args:
        task: Task

    Returns:
        calculate_pert_estimate(task.estimate) if task.estimate else 8.0
    """
    has_est = None  # TODO: Check if task has estimate
    hours = None  # TODO: Calculate PERT if has estimate, else default
    return calculate_pert_estimate(task.estimate) if task.estimate else 8.0


def calculate_total_hours(tasks: list[Task]) -> float:
    """
    Calculate total estimated hours for a list of tasks.

    Args:
        tasks: list of Task

    Returns:
        sum(calculate_task_hours(t) for t in tasks)
    """
    hours_list = None  # TODO: Calculate hours for each task
    total = None  # TODO: Sum all hours
    return sum(calculate_task_hours(t) for t in tasks)


def calculate_user_workload(user: User, tasks: list[Task]) -> Any:
    """
    Calculate workload report for a user.

    Args:
        user: User
        tasks: list of Task

    Returns:
        WorkloadReport(user_id=user.id, total_tasks=len(get_user_tasks(tasks, user.id)), pending_tasks=len([t for t in get_user_tasks(tasks, user.id) if t.status.value == "pending"]), in_progress_tasks=len([t for t in get_user_tasks(tasks, user.id) if t.status.value == "in_progress"]), completed_tasks=len([t for t in get_user_tasks(tasks, user.id) if t.status.value == "completed"]), total_estimated_hours=calculate_total_hours([t for t in get_user_tasks(tasks, user.id) if not is_task_terminal(t)]), utilization_percent=min(100, calculate_total_hours([t for t in get_user_tasks(tasks, user.id) if not is_task_terminal(t)]) / max(user.capacity, 1) * 100))
    """
    user_tasks = None  # TODO: Filter tasks assigned to user
    counts = None  # TODO: Count by status
    estimated_hours = None  # TODO: Sum estimates for incomplete tasks
    util_percent = None  # TODO: Calculate utilization
    return WorkloadReport(user_id=user.id, total_tasks=len(get_user_tasks(tasks, user.id)), pending_tasks=len([t for t in get_user_tasks(tasks, user.id) if t.status.value == "pending"]), in_progress_tasks=len([t for t in get_user_tasks(tasks, user.id) if t.status.value == "in_progress"]), completed_tasks=len([t for t in get_user_tasks(tasks, user.id) if t.status.value == "completed"]), total_estimated_hours=calculate_total_hours([t for t in get_user_tasks(tasks, user.id) if not is_task_terminal(t)]), utilization_percent=min(100, calculate_total_hours([t for t in get_user_tasks(tasks, user.id) if not is_task_terminal(t)]) / max(user.capacity, 1) * 100))


def calculate_team_workload(users: list[User], tasks: list[Task]) -> Any:
    """
    Calculate combined workload for a team.

    Args:
        users: list of User
        tasks: list of Task

    Returns:
        WorkloadReport(user_id="team", total_tasks=len(tasks), pending_tasks=len([t for t in tasks if t.status.value == "pending"]), in_progress_tasks=len([t for t in tasks if t.status.value == "in_progress"]), completed_tasks=len([t for t in tasks if t.status.value == "completed"]), total_estimated_hours=calculate_total_hours([t for t in tasks if not is_task_terminal(t)]), utilization_percent=min(100, sum(calculate_user_workload(u, tasks).utilization_percent for u in users) / max(len(users), 1)))
    """
    workloads = None  # TODO: Calculate workload for each user
    team_totals = None  # TODO: Aggregate totals
    return WorkloadReport(user_id="team", total_tasks=len(tasks), pending_tasks=len([t for t in tasks if t.status.value == "pending"]), in_progress_tasks=len([t for t in tasks if t.status.value == "in_progress"]), completed_tasks=len([t for t in tasks if t.status.value == "completed"]), total_estimated_hours=calculate_total_hours([t for t in tasks if not is_task_terminal(t)]), utilization_percent=min(100, sum(calculate_user_workload(u, tasks).utilization_percent for u in users) / max(len(users), 1)))


def find_least_loaded_user(users: list[User], tasks: list[Task]) -> float:
    """
    Find user with lowest current workload.

    Args:
        users: list of User
        tasks: list of Task

    Returns:
        min(users, key=lambda u: calculate_user_workload(u, tasks).utilization_percent)
    """
    if not (len(users) > 0):
        raise ValueError('No users provided')
    workloads = None  # TODO: Calculate workload for each user
    min_load = None  # TODO: Find minimum utilization
    least_loaded = None  # TODO: Return user with minimum
    return min(users, key=lambda u: calculate_user_workload(u, tasks).utilization_percent)


def find_most_loaded_user(users: list[User], tasks: list[Task]) -> float:
    """
    Find user with highest current workload.

    Args:
        users: list of User
        tasks: list of Task

    Returns:
        max(users, key=lambda u: calculate_user_workload(u, tasks).utilization_percent)
    """
    if not (len(users) > 0):
        raise ValueError('No users provided')
    workloads = None  # TODO: Calculate workload for each user
    max_load = None  # TODO: Find maximum utilization
    most_loaded = None  # TODO: Return user with maximum
    return max(users, key=lambda u: calculate_user_workload(u, tasks).utilization_percent)


def get_overloaded_users(users: list[User], tasks: list[Task], threshold: float) -> Any:
    """
    Find users whose utilization exceeds threshold.

    Args:
        users: list of User
        tasks: list of Task
        threshold: number

    Returns:
        [u for u in users if calculate_user_workload(u, tasks).utilization_percent > threshold]
    """
    workloads = None  # TODO: Calculate workload for each user
    overloaded = None  # TODO: Filter to those over threshold
    return [u for u in users if calculate_user_workload(u, tasks).utilization_percent > threshold]


def balance_workload(users: list[User], tasks: list[Task], threshold: float) -> Any:
    """
    Suggest task reassignments to balance workload.

    Args:
        users: list of User
        tasks: list of Task
        threshold: number

    Returns:
        [ReassignmentSuggestion(task_id=t.id, from_user_id=t.assignee_id or "", to_user_id=find_least_loaded_user(users, tasks).id, reason="Workload balancing") for u in get_overloaded_users(users, tasks, threshold) for t in get_user_tasks(tasks, u.id)[:1]]
    """
    workloads = None  # TODO: Calculate workloads for all users
    # Find overloaded and underloaded users -> over, under
    suggestions = None  # TODO: Generate reassignment suggestions
    return [ReassignmentSuggestion(task_id=t.id, from_user_id=t.assignee_id or "", to_user_id=find_least_loaded_user(users, tasks).id, reason="Workload balancing") for u in get_overloaded_users(users, tasks, threshold) for t in get_user_tasks(tasks, u.id)[:1]]


def calculate_workflow_progress(workflow: Workflow) -> float:
    """
    Calculate completion percentage of a workflow.

    Args:
        workflow: Workflow

    Returns:
        len([t for t in workflow.tasks if t.status.value == "completed"]) / len(workflow.tasks) * 100
    """
    if not (len(workflow.tasks) > 0):
        raise ValueError('Workflow has no tasks')
    completed = None  # TODO: Count completed tasks
    total = None  # TODO: Count total tasks
    percent = None  # TODO: Calculate percentage
    return len([t for t in workflow.tasks if t.status.value == "completed"]) / len(workflow.tasks) * 100


def calculate_remaining_work(tasks: list[Task]) -> Any:
    """
    Calculate total remaining work in hours.

    Args:
        tasks: list of Task

    Returns:
        calculate_total_hours([t for t in tasks if not is_task_terminal(t)])
    """
    incomplete = None  # TODO: Filter to incomplete tasks
    total_hours = None  # TODO: Sum PERT estimates
    return calculate_total_hours([t for t in tasks if not is_task_terminal(t)])


def calculate_completed_work(tasks: list[Task]) -> float:
    """
    Calculate total completed work in hours.

    Args:
        tasks: list of Task

    Returns:
        sum(t.actual_hours for t in tasks if t.status.value == "completed")
    """
    completed = None  # TODO: Filter to completed tasks
    total_hours = None  # TODO: Sum actual hours
    return sum(t.actual_hours for t in tasks if t.status.value == "completed")


def calculate_velocity(tasks: list[Task], start_time: float, end_time: float) -> Any:
    """
    Calculate team velocity in hours per day.

    Args:
        tasks: list of Task
        start_time: number
        end_time: number

    Returns:
        calculate_completed_work(tasks) / max((end_time - start_time) / 86400, 1)
    """
    if not (end_time > start_time):
        raise ValueError('End time must be after start time')
    completed_hours = None  # TODO: Calculate completed work in period
    days = None  # TODO: Calculate days elapsed
    velocity = None  # TODO: Divide hours by days
    return calculate_completed_work(tasks) / max((end_time - start_time) / 86400, 1)


def estimate_completion_date(workflow: Workflow, current_time: float, velocity_hours_per_day: float) -> Any:
    """
    Estimate when workflow will complete.

    Args:
        workflow: Workflow
        current_time: number
        velocity_hours_per_day: number

    Returns:
        current_time + (calculate_remaining_work(workflow.tasks) / velocity_hours_per_day) * 86400
    """
    if not (velocity_hours_per_day > 0):
        raise ValueError('Velocity must be positive')
    remaining_hours = None  # TODO: Calculate remaining work
    days_needed = None  # TODO: Calculate days needed
    completion_date = None  # TODO: Add to current time
    return current_time + (calculate_remaining_work(workflow.tasks) / velocity_hours_per_day) * 86400


def is_workflow_on_track(workflow: Workflow, current_time: float, velocity_hours_per_day: float) -> Any:
    """
    Check if workflow is on track to meet deadline.

    Args:
        workflow: Workflow
        current_time: number
        velocity_hours_per_day: number

    Returns:
        workflow.deadline is None or estimate_completion_date(workflow, current_time, velocity_hours_per_day) <= workflow.deadline
    """
    est_completion = None  # TODO: Estimate completion date
    on_track = None  # TODO: Compare to deadline
    return workflow.deadline is None or estimate_completion_date(workflow, current_time, velocity_hours_per_day) <= workflow.deadline


def calculate_critical_path_length(tasks: list[Task]) -> float:
    """
    Calculate the length of the critical path in hours.

    Args:
        tasks: list of Task

    Returns:
        max([calculate_task_hours(t) * get_dependency_depth(t, tasks) for t in tasks], default=0)
    """
    sorted_tasks = None  # TODO: Sort tasks topologically
    critical_path = None  # TODO: Calculate longest path through graph
    total_hours = None  # TODO: Sum estimates along path
    return max([calculate_task_hours(t) * get_dependency_depth(t, tasks) for t in tasks], default=0)


def calculate_workflow_metrics(workflow: Workflow, current_time: float, velocity_hours_per_day: float) -> Any:
    """
    Calculate comprehensive metrics for a workflow.

    Args:
        workflow: Workflow
        current_time: number
        velocity_hours_per_day: number

    Returns:
        WorkflowMetrics(workflow_id=workflow.id, total_tasks=len(workflow.tasks), completed_tasks=len([t for t in workflow.tasks if t.status.value == "completed"]), blocked_tasks=len([t for t in workflow.tasks if t.status.value == "blocked"]), completion_percent=calculate_workflow_progress(workflow), estimated_completion_date=estimate_completion_date(workflow, current_time, velocity_hours_per_day), is_on_track=is_workflow_on_track(workflow, current_time, velocity_hours_per_day), critical_path_length=calculate_critical_path_length(workflow.tasks))
    """
    counts = None  # TODO: Count tasks by status
    progress = None  # TODO: Calculate progress percentage
    est_completion = None  # TODO: Estimate completion date
    on_track = None  # TODO: Determine if on track
    critical_length = None  # TODO: Calculate critical path
    return WorkflowMetrics(workflow_id=workflow.id, total_tasks=len(workflow.tasks), completed_tasks=len([t for t in workflow.tasks if t.status.value == "completed"]), blocked_tasks=len([t for t in workflow.tasks if t.status.value == "blocked"]), completion_percent=calculate_workflow_progress(workflow), estimated_completion_date=estimate_completion_date(workflow, current_time, velocity_hours_per_day), is_on_track=is_workflow_on_track(workflow, current_time, velocity_hours_per_day), critical_path_length=calculate_critical_path_length(workflow.tasks))


def create_workflow(id: str, name: str, owner_id: str, timestamp: float) -> Any:
    """
    Create a new workflow in draft status.

    Args:
        id: string
        name: string
        owner_id: string
        timestamp: number

    Returns:
        Workflow(id=id, name=name, description="", status=WorkflowStatus(value="draft"), owner_id=owner_id, tasks=[], created_at=timestamp, started_at=None, completed_at=None, deadline=None)
    """
    workflow = None  # TODO: Create workflow with draft status
    return Workflow(id=id, name=name, description="", status=WorkflowStatus(value="draft"), owner_id=owner_id, tasks=[], created_at=timestamp, started_at=None, completed_at=None, deadline=None)


def add_task_to_workflow(workflow: Workflow, task: Task) -> Any:
    """
    Add a task to a workflow.

    Args:
        workflow: Workflow
        task: Task

    Returns:
        Workflow(id=workflow.id, name=workflow.name, description=workflow.description, status=workflow.status, owner_id=workflow.owner_id, tasks=workflow.tasks + [task], created_at=workflow.created_at, started_at=workflow.started_at, completed_at=workflow.completed_at, deadline=workflow.deadline)
    """
    if not (workflow.status.value == "draft"):
        raise ValueError('Can only add tasks to draft workflows')
    updated = None  # TODO: Append task to workflow tasks
    return Workflow(id=workflow.id, name=workflow.name, description=workflow.description, status=workflow.status, owner_id=workflow.owner_id, tasks=workflow.tasks + [task], created_at=workflow.created_at, started_at=workflow.started_at, completed_at=workflow.completed_at, deadline=workflow.deadline)


def remove_task_from_workflow(workflow: Workflow, task_id: str) -> Any:
    """
    Remove a task from a workflow.

    Args:
        workflow: Workflow
        task_id: string

    Returns:
        Workflow(id=workflow.id, name=workflow.name, description=workflow.description, status=workflow.status, owner_id=workflow.owner_id, tasks=[t for t in workflow.tasks if t.id != task_id], created_at=workflow.created_at, started_at=workflow.started_at, completed_at=workflow.completed_at, deadline=workflow.deadline)
    """
    if not (workflow.status.value == "draft"):
        raise ValueError('Can only remove tasks from draft workflows')
    updated = None  # TODO: Filter out task with ID
    return Workflow(id=workflow.id, name=workflow.name, description=workflow.description, status=workflow.status, owner_id=workflow.owner_id, tasks=[t for t in workflow.tasks if t.id != task_id], created_at=workflow.created_at, started_at=workflow.started_at, completed_at=workflow.completed_at, deadline=workflow.deadline)


def activate_workflow(workflow: Workflow, timestamp: float) -> Any:
    """
    Activate a draft workflow.

    Args:
        workflow: Workflow
        timestamp: number

    Returns:
        Workflow(id=workflow.id, name=workflow.name, description=workflow.description, status=WorkflowStatus(value="active"), owner_id=workflow.owner_id, tasks=workflow.tasks, created_at=workflow.created_at, started_at=timestamp, completed_at=workflow.completed_at, deadline=workflow.deadline)
    """
    if not (workflow.status.value == "draft"):
        raise ValueError('Can only activate draft workflows')
    if not (len(workflow.tasks) > 0):
        raise ValueError('Cannot activate empty workflow')
    if not (not detect_circular_dependencies(workflow.tasks)):
        raise ValueError('Workflow has circular dependencies')
    updated = None  # TODO: Update status to active
    final = None  # TODO: Set started_at timestamp
    return Workflow(id=workflow.id, name=workflow.name, description=workflow.description, status=WorkflowStatus(value="active"), owner_id=workflow.owner_id, tasks=workflow.tasks, created_at=workflow.created_at, started_at=timestamp, completed_at=workflow.completed_at, deadline=workflow.deadline)


def pause_workflow(workflow: Workflow) -> Any:
    """
    Pause an active workflow.

    Args:
        workflow: Workflow

    Returns:
        Workflow(id=workflow.id, name=workflow.name, description=workflow.description, status=WorkflowStatus(value="paused"), owner_id=workflow.owner_id, tasks=workflow.tasks, created_at=workflow.created_at, started_at=workflow.started_at, completed_at=workflow.completed_at, deadline=workflow.deadline)
    """
    if not (workflow.status.value == "active"):
        raise ValueError('Can only pause active workflows')
    updated = None  # TODO: Update status to paused
    return Workflow(id=workflow.id, name=workflow.name, description=workflow.description, status=WorkflowStatus(value="paused"), owner_id=workflow.owner_id, tasks=workflow.tasks, created_at=workflow.created_at, started_at=workflow.started_at, completed_at=workflow.completed_at, deadline=workflow.deadline)


def resume_workflow(workflow: Workflow) -> Any:
    """
    Resume a paused workflow.

    Args:
        workflow: Workflow

    Returns:
        Workflow(id=workflow.id, name=workflow.name, description=workflow.description, status=WorkflowStatus(value="active"), owner_id=workflow.owner_id, tasks=workflow.tasks, created_at=workflow.created_at, started_at=workflow.started_at, completed_at=workflow.completed_at, deadline=workflow.deadline)
    """
    if not (workflow.status.value == "paused"):
        raise ValueError('Can only resume paused workflows')
    updated = None  # TODO: Update status to active
    return Workflow(id=workflow.id, name=workflow.name, description=workflow.description, status=WorkflowStatus(value="active"), owner_id=workflow.owner_id, tasks=workflow.tasks, created_at=workflow.created_at, started_at=workflow.started_at, completed_at=workflow.completed_at, deadline=workflow.deadline)


def all_tasks_terminal(tasks: list[Task]) -> Any:
    """
    Check if all tasks in a list are terminal.

    Args:
        tasks: list of Task

    Returns:
        all(is_task_terminal(t) for t in tasks)
    """
    all_done = None  # TODO: Check each task is terminal
    return all(is_task_terminal(t) for t in tasks)


def complete_workflow(workflow: Workflow, timestamp: float) -> Any:
    """
    Mark a workflow as completed.

    Args:
        workflow: Workflow
        timestamp: number

    Returns:
        Workflow(id=workflow.id, name=workflow.name, description=workflow.description, status=WorkflowStatus(value="completed"), owner_id=workflow.owner_id, tasks=workflow.tasks, created_at=workflow.created_at, started_at=workflow.started_at, completed_at=timestamp, deadline=workflow.deadline)
    """
    if not (workflow.status.value == "active"):
        raise ValueError('Can only complete active workflows')
    if not (all_tasks_terminal(workflow.tasks)):
        raise ValueError('Cannot complete workflow with pending tasks')
    updated = None  # TODO: Update status to completed
    final = None  # TODO: Set completed_at timestamp
    return Workflow(id=workflow.id, name=workflow.name, description=workflow.description, status=WorkflowStatus(value="completed"), owner_id=workflow.owner_id, tasks=workflow.tasks, created_at=workflow.created_at, started_at=workflow.started_at, completed_at=timestamp, deadline=workflow.deadline)


def archive_workflow(workflow: Workflow) -> Any:
    """
    Archive a completed workflow.

    Args:
        workflow: Workflow

    Returns:
        Workflow(id=workflow.id, name=workflow.name, description=workflow.description, status=WorkflowStatus(value="archived"), owner_id=workflow.owner_id, tasks=workflow.tasks, created_at=workflow.created_at, started_at=workflow.started_at, completed_at=workflow.completed_at, deadline=workflow.deadline)
    """
    if not (workflow.status.value == "completed"):
        raise ValueError('Can only archive completed workflows')
    updated = None  # TODO: Update status to archived
    return Workflow(id=workflow.id, name=workflow.name, description=workflow.description, status=WorkflowStatus(value="archived"), owner_id=workflow.owner_id, tasks=workflow.tasks, created_at=workflow.created_at, started_at=workflow.started_at, completed_at=workflow.completed_at, deadline=workflow.deadline)


def filter_tasks_by_status(tasks: list[Task], status: TaskStatus) -> Any:
    """
    Filter tasks to those matching a status.

    Args:
        tasks: list of Task
        status: TaskStatus

    Returns:
        [t for t in tasks if t.status.value == status.value]
    """
    return [t for t in tasks if t.status.value == status.value]


def filter_tasks_by_priority(tasks: list[Task], priority: Priority) -> Any:
    """
    Filter tasks to those matching a priority.

    Args:
        tasks: list of Task
        priority: Priority

    Returns:
        [t for t in tasks if t.priority.value == priority.value]
    """
    return [t for t in tasks if t.priority.value == priority.value]


def filter_tasks_by_assignee(tasks: list[Task], user_id: str) -> Any:
    """
    Filter tasks to those assigned to a user.

    Args:
        tasks: list of Task
        user_id: string

    Returns:
        [t for t in tasks if t.assignee_id == user_id]
    """
    return [t for t in tasks if t.assignee_id == user_id]


def filter_unassigned_tasks(tasks: list[Task]) -> Any:
    """
    Filter to tasks with no assignee.

    Args:
        tasks: list of Task

    Returns:
        [t for t in tasks if t.assignee_id is None]
    """
    unassigned = None  # TODO: Filter to tasks where assignee_id is None
    return [t for t in tasks if t.assignee_id is None]


def filter_overdue_tasks(tasks: list[Task], current_time: float) -> Any:
    """
    Filter tasks that are past their due date.

    Args:
        tasks: list of Task
        current_time: number

    Returns:
        [t for t in tasks if t.due_date is not None and t.due_date < current_time and not is_task_terminal(t)]
    """
    with_due = None  # TODO: Filter to tasks with due_date set
    overdue = None  # TODO: Filter to non-terminal past due
    return [t for t in tasks if t.due_date is not None and t.due_date < current_time and not is_task_terminal(t)]


def filter_tasks_due_soon(tasks: list[Task], current_time: float, window_hours: float) -> Any:
    """
    Filter tasks due within a time window.

    Args:
        tasks: list of Task
        current_time: number
        window_hours: number

    Returns:
        [t for t in tasks if t.due_date is not None and current_time <= t.due_date <= current_time + window_hours * 3600 and not is_task_terminal(t)]
    """
    threshold = None  # TODO: Calculate deadline threshold
    due_soon = None  # TODO: Filter tasks due before threshold
    return [t for t in tasks if t.due_date is not None and current_time <= t.due_date <= current_time + window_hours * 3600 and not is_task_terminal(t)]


def search_tasks_by_tag(tasks: list[Task], tag: str) -> Any:
    """
    Find tasks that have a specific tag.

    Args:
        tasks: list of Task
        tag: string

    Returns:
        [t for t in tasks if tag in t.tags]
    """
    return [t for t in tasks if tag in t.tags]


def search_tasks_by_title(tasks: list[Task], search_term: str) -> Any:
    """
    Find tasks with title containing search term.

    Args:
        tasks: list of Task
        search_term: string

    Returns:
        [t for t in tasks if search_term.lower() in t.title.lower()]
    """
    matching = None  # TODO: Filter tasks where title contains term
    return [t for t in tasks if search_term.lower() in t.title.lower()]


def sort_tasks_by_priority(tasks: list[Task]) -> Any:
    """
    Sort tasks by priority highest first.

    Args:
        tasks: list of Task

    Returns:
        sorted(tasks, key=lambda t: priority_to_weight(t.priority), reverse=True)
    """
    sorted_tasks = None  # TODO: Sort using priority weight as key
    return sorted(tasks, key=lambda t: priority_to_weight(t.priority), reverse=True)


def sort_tasks_by_due_date(tasks: list[Task]) -> Any:
    """
    Sort tasks by due date earliest first.

    Args:
        tasks: list of Task

    Returns:
        sorted([t for t in tasks if t.due_date is not None], key=lambda t: cast(float, t.due_date)) + [t for t in tasks if t.due_date is None]
    """
    # Separate tasks with and without due dates -> with_due, no_due
    sorted_due = None  # TODO: Sort tasks with due dates
    combined = None  # TODO: Append tasks without due dates
    return sorted([t for t in tasks if t.due_date is not None], key=lambda t: cast(float, t.due_date)) + [t for t in tasks if t.due_date is None]


def sort_tasks_by_created_date(tasks: list[Task]) -> Any:
    """
    Sort tasks by creation date oldest first.

    Args:
        tasks: list of Task

    Returns:
        sorted(tasks, key=lambda t: t.created_at)
    """
    sorted_tasks = None  # TODO: Sort by created_at ascending
    return sorted(tasks, key=lambda t: t.created_at)


def generate_status_summary(tasks: list[Task]) -> Any:
    """
    Generate a summary of task counts by status.

    Args:
        tasks: list of Task

    Returns:
        get_status_counts(tasks)
    """
    counts = None  # TODO: Get status counts
    return get_status_counts(tasks)


def generate_priority_summary(tasks: list[Task]) -> Any:
    """
    Generate a summary of task counts by priority.

    Args:
        tasks: list of Task

    Returns:
        PriorityCounts(critical=len([t for t in tasks if t.priority.value == "critical"]), high=len([t for t in tasks if t.priority.value == "high"]), medium=len([t for t in tasks if t.priority.value == "medium"]), low=len([t for t in tasks if t.priority.value == "low"]))
    """
    critical = None  # TODO: Count critical tasks
    high = None  # TODO: Count high tasks
    medium = None  # TODO: Count medium tasks
    low = None  # TODO: Count low tasks
    return PriorityCounts(critical=len([t for t in tasks if t.priority.value == "critical"]), high=len([t for t in tasks if t.priority.value == "high"]), medium=len([t for t in tasks if t.priority.value == "medium"]), low=len([t for t in tasks if t.priority.value == "low"]))


def calculate_average_completion_time(tasks: list[Task]) -> float:
    """
    Calculate average time to complete tasks.

    Args:
        tasks: list of Task

    Returns:
        sum((t.completed_at - t.created_at) / 3600 for t in tasks if t.status.value == "completed" and t.completed_at is not None) / max(len([t for t in tasks if t.status.value == "completed" and t.completed_at is not None]), 1)
    """
    completed = None  # TODO: Filter to completed tasks with timestamps
    durations = None  # TODO: Calculate duration for each
    avg_time = None  # TODO: Average the durations
    return sum((t.completed_at - t.created_at) / 3600 for t in tasks if t.status.value == "completed" and t.completed_at is not None) / max(len([t for t in tasks if t.status.value == "completed" and t.completed_at is not None]), 1)


def calculate_estimation_accuracy(tasks: list[Task]) -> float:
    """
    Calculate how accurate estimates were vs actual.

    Args:
        tasks: list of Task

    Returns:
        sum(calculate_pert_estimate(t.estimate) / max(t.actual_hours, 0.1) for t in tasks if t.estimate is not None and t.actual_hours > 0) / max(len([t for t in tasks if t.estimate is not None and t.actual_hours > 0]), 1) * 100
    """
    with_data = None  # TODO: Filter to tasks with estimates and actuals
    ratios = None  # TODO: Calculate estimate vs actual ratio for each
    accuracy = None  # TODO: Average the ratios
    return sum(calculate_pert_estimate(t.estimate) / max(t.actual_hours, 0.1) for t in tasks if t.estimate is not None and t.actual_hours > 0) / max(len([t for t in tasks if t.estimate is not None and t.actual_hours > 0]), 1) * 100


def generate_user_performance_report(user: User, tasks: list[Task], period_start: float, period_end: float) -> Any:
    """
    Generate performance metrics for a user.

    Args:
        user: User
        tasks: list of Task
        period_start: number
        period_end: number

    Returns:
        {"user_id": user.id, "completed_tasks": len([t for t in get_user_tasks(tasks, user.id) if t.status.value == "completed" and t.completed_at is not None and period_start <= t.completed_at <= period_end]), "avg_completion_hours": calculate_average_completion_time([t for t in get_user_tasks(tasks, user.id) if t.completed_at is not None and period_start <= t.completed_at <= period_end]), "estimation_accuracy": calculate_estimation_accuracy([t for t in get_user_tasks(tasks, user.id) if t.completed_at is not None and period_start <= t.completed_at <= period_end])}
    """
    user_tasks = None  # TODO: Get user tasks in period
    completed = None  # TODO: Calculate completed count
    avg_time = None  # TODO: Calculate average completion time
    accuracy = None  # TODO: Calculate estimation accuracy
    return {"user_id": user.id, "completed_tasks": len([t for t in get_user_tasks(tasks, user.id) if t.status.value == "completed" and t.completed_at is not None and period_start <= t.completed_at <= period_end]), "avg_completion_hours": calculate_average_completion_time([t for t in get_user_tasks(tasks, user.id) if t.completed_at is not None and period_start <= t.completed_at <= period_end]), "estimation_accuracy": calculate_estimation_accuracy([t for t in get_user_tasks(tasks, user.id) if t.completed_at is not None and period_start <= t.completed_at <= period_end])}


def generate_workflow_summary(workflow: Workflow, current_time: float, velocity_hours_per_day: float) -> Any:
    """
    Generate executive summary of workflow status.

    Args:
        workflow: Workflow
        current_time: number
        velocity_hours_per_day: number

    Returns:
        {"workflow_id": workflow.id, "name": workflow.name, "status": workflow.status.value, "progress_percent": calculate_workflow_progress(workflow) if len(workflow.tasks) > 0 else 0, "is_on_track": is_workflow_on_track(workflow, current_time, velocity_hours_per_day) if velocity_hours_per_day > 0 else True}
    """
    metrics = None  # TODO: Calculate metrics
    summary = None  # TODO: Generate summary text
    return {"workflow_id": workflow.id, "name": workflow.name, "status": workflow.status.value, "progress_percent": calculate_workflow_progress(workflow) if len(workflow.tasks) > 0 else 0, "is_on_track": is_workflow_on_track(workflow, current_time, velocity_hours_per_day) if velocity_hours_per_day > 0 else True}
