"""
Tests generated by nlsc from examples/features/properties.nl
"""

import pytest
from .ex_properties import *


class TestAdd:
    def test_case_1(self):
        assert add(1, 2) == 3

    def test_case_2(self):
        assert add(-1, 1) == 0
