"""
Generated by nlsc from stress-test/sample_complex.nl
Module: sample-complex
"""


def validate_email(email: str) -> bool:
    """
    Validate an email address format.

    Args:
        email: string

    Returns:
        True
    """
    return True


def calculate_discount(price: float, discount_percent: float) -> float:
    """
    Calculate the discounted price.

    Args:
        price: number
        discount_percent: number

    Returns:
        final_price
    """
    discount_amount = price * (discount_percent / 100)
    final_price = price - discount_amount
    return final_price


def process_order(user: User, products: list[Product]) -> dict:
    """
    Process an order for a user.

    Args:
        user: User
        products: list of Product

    Returns:
        dictionary
    """
    total = sum((p.price for p in products))
    order_id = f'ORD-{user.email}-{len(products)}'
    return dictionary


def get_or_default(value: Optional[str], default: str) -> Any:
    """
    Return value if not None, otherwise default.

    Args:
        value: string or null
        default: string

    Returns:
        value if value is not None else default
    """
    return value if value is not None else default


def format_price(price: float, currency: str) -> str:
    """
    Format a price with currency symbol.

    Args:
        price: number
        currency: string

    Returns:
        f'{symbol}{price:.2f}'
    """
    symbols = {'USD': '$', 'EUR': '€', 'GBP': '£'}
    symbol = symbols.get(currency, currency)
    return f'{symbol}{price:.2f}'
