"""
Generated by nlsc from stress-test/stdlib_patterns.nl
Module: stdlib-patterns
"""


def parse_json_safe(text: str) -> Any:
    """
    Parse JSON string safely, returning None on error.

    Args:
        text: string

    Returns:
        json.loads(text)
    """
    return json.loads(text)


def flatten_list(nested: list[list[Any]]) -> list:
    """
    Flatten a nested list by one level.

    Args:
        nested: list of list of any

    Returns:
        result
    """
    result = []
    return result


def dict_merge(base: dict, update: dict) -> Any:
    """
    Merge two dictionaries, with update taking precedence.

    Args:
        base: dictionary
        update: dictionary

    Returns:
        merged
    """
    merged = dict(base)
    return merged


def safe_divide(a: float, b: float, default: float) -> float:
    """
    Divide a by b, returning default if b is zero.

    Args:
        a: number
        b: number
        default: number

    Returns:
        a / b
    """
    return a / b


def clamp(value: float, minimum: float, maximum: float) -> Any:
    """
    Clamp a value between minimum and maximum.

    Args:
        value: number
        minimum: number
        maximum: number

    Returns:
        max(minimum, min(maximum, value))
    """
    return max(minimum, min(maximum, value))


def pluralize(word: str, count: float) -> str:
    """
    Return singular or plural form based on count.

    Args:
        word: string
        count: number

    Returns:
        word + 's'
    """
    return word + 's'
